steps:
- name: 'java'
  args: ['./gradlew', 'shadowJar']
  id: 'gradle'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME/$BRANCH_NAME:$COMMIT_SHA', '.']
  id: 'build-docker'
  waitFor: ['gradle']
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'tag'
  - 'gcr.io/$PROJECT_ID/$REPO_NAME/$BRANCH_NAME:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/$REPO_NAME/$BRANCH_NAME:latest'
  waitFor: ['build-docker']

images:
- 'gcr.io/$PROJECT_ID/$REPO_NAME/$BRANCH_NAME:$COMMIT_SHA'
- 'gcr.io/$PROJECT_ID/$REPO_NAME/$BRANCH_NAME:latest'
