---
swagger: "2.0"
info:
  description: "A simple Google Cloud Endpoints API example."
  title: "Endpoints Example"
  version: "1.0.0"
host: "echo-api.endpoints.tvlk-realtime-tokyo-test.cloud.goog"
basePath: "/"
paths:
  /hello-world:
    get:
      operationId: "sayHello"
      produces:
      - "application/json"
      parameters:
      - name: "name"
        in: "query"
        required: false
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Saying"
          headers: {}
definitions:
  Saying:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
        readOnly: true
      content:
        type: "string"
        readOnly: true
